# Prettier Options
# https://prettier.io/docs/en/options.html

printWidth: 130
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
proseWrap: preserve
htmlWhitespaceSensitivity: css
endOfLine: auto
